## Оптимизация выполнения кода, векторизация, Numba

Материалы:
* Макрушин С.В. Лекция 3: Оптимизация выполнения кода, векторизация, Numba
* IPython Cookbook, Second Edition (2018), глава 4
* https://numba.pydata.org/numba-doc/latest/user/5minguide.html

## Разминка

1. Сгенерируйте массив `A` из `N=1млн` случайных целых чисел на отрезке от 0 до 1000. Пусть `B[i] = A[i] + 100`. Посчитайте среднее значение массива `B`.

In [53]:
A = np.random.randint(0, 1000, size=(1000000,))

In [66]:
def f1(A):
    acc, cnt = 0, 0
    for x in A:
        acc += (x + 100)
        cnt += 1
    return acc / cnt

def f2(A):
    acc = 0
    for x in A:
        acc += (x + 100)
    return acc / len(A)

def f3(A):
    acc = 0
    for x in A:
        acc += x
    return acc / len(A) + 100

@njit
def f4(A):
    acc, cnt = 0, 0
    for x in A:
        acc += (x + 100)
        cnt += 1
    return acc / cnt

@njit
def f5(A):
    acc = 0
    for x in A:
        acc += x
    return acc / len(A) + 100

In [59]:
%timeit f1(A)

532 ms ± 15.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [60]:
%timeit f2(A)

412 ms ± 40.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [62]:
%timeit f3(A)

167 ms ± 3.74 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [65]:
%timeit f4(A)

391 µs ± 38.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [68]:
%timeit f5(A)

379 µs ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

2. Создайте таблицу 2млн строк и с 4 столбцами, заполненными случайными числами. Добавьте столбец `key`, которые содержит элементы из множества английских букв. Выберите из таблицы подмножество строк, для которых в столбце `key` указаны первые 5 английских букв.

In [95]:
import string
N = 2_000_000
df = pd.DataFrame(np.random.randn(N, 4), columns=[f'col{i}' for i in range(4)])
df['key'] = np.random.choice(list(string.ascii_letters.lower()), N, replace=True)

In [96]:
def g1(df):
    res = pd.DataFrame()
    for letter in ['a', 'b', 'c', 'd', 'e']:
        res = pd.concat([res, df[df['key']==letter]], axis=0)
    return res

def g2(df):
    res = pd.concat([df[df['key']==letter] for letter in ['a', 'b', 'c', 'd', 'e']], axis=0)
    return res

@njit
def g3(df): # ERROR
    res = pd.DataFrame()
    for letter in ['a', 'b', 'c', 'd', 'e']:
        res = pd.concat([res, df[df['key']==letter]], axis=0)
    return res

def g4(df):
    res = df[df['key'].isin(['a', 'b', 'c', 'd', 'e'])]
    return res

In [97]:
%timeit g1(df)

1.04 s ± 26.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [98]:
%timeit g2(df)

1.01 s ± 31 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [99]:
%timeit g4(df)

152 ms ± 5.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

## Лабораторная работа 3

In [ ]:
# !pip install line_profiler

In [41]:
import numpy as np
import pandas as pd
from numba import jit, njit

%load_ext line_profiler

The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler

1. В файлах `recipes_short.csv` и `reviews_short.csv` находится информация об рецептах блюд и отзывах на эти рецепты соответственно. Загрузите данные из файлов в виде `pd.DataFrame` с названиями `recipes` и `reviews`. Обратите внимание на корректное считывание столбца(ов) с индексами. Приведите столбцы к нужным типам.

In [2]:
recipes = pd.read_csv(r"E:\Downloads\TOBD_2021_datasets\food_com\data\recipes_short.csv", parse_dates=['submitted'])
reviews = pd.read_csv(r"E:\Downloads\TOBD_2021_datasets\food_com\data\reviews_short.csv", index_col=0, parse_dates=['date'])

In [14]:
recipes.head(2)

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN

In [15]:
reviews.head(2)

,user_id,recipe_id,date,rating,review
370476,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
624300,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...

2. Реализуйте несколько вариантов функции подсчета среднего значения столбца `rating` из таблицы `reviews` для отзывов, оставленных в 2010 году.
    1. С использованием метода `DataFrame.iterrows` и без использования срезов таблицы
    2. С использованием метода `DataFrame.iterrows` и с использованием срезов таблицы
    3. С использованием метода `DataFrame.mean`

Проверьте, что результаты работы всех написанных функций корректны и совпадают. Измерьте выполнения всех вариантов.

In [20]:
def get_mean_rating_of_2010(df):
    acc, cnt = 0, 0
    for index, row in df.iterrows():
        if row['date'].year == 2010:
            acc += row['rating']
            cnt += 1
    return acc / cnt

def get_mean_rating_of_2010_v2(df):
    acc, cnt = 0, 0
    df = df[df['date'].dt.year == 2010]
    for index, row in df.iterrows():
        acc += row['rating']
        cnt += 1
    return acc / cnt

def get_mean_rating_of_2010_v3(df):
    rating = df[df['date'].dt.year == 2010]['rating']
    acc = sum(df['rating'])
    return acc / len(rating)

def get_mean_rating_of_2010_v4(df):
    return df[df['date'].dt.year == 2010]['rating'].mean()

In [21]:
%timeit -r 2 get_mean_rating_of_2010(reviews)

20.7 s ± 97 ms per loop (mean ± std. dev. of 2 runs, 1 loop each)

In [22]:
%timeit -r 2 get_mean_rating_of_2010_v2(reviews)

1.97 s ± 9.27 ms per loop (mean ± std. dev. of 2 runs, 1 loop each)

In [23]:
%timeit -r 2 get_mean_rating_of_2010_v3(reviews)

33 ms ± 6.1 µs per loop (mean ± std. dev. of 2 runs, 10 loops each)

In [25]:
%timeit -r 2 get_mean_rating_of_2010_v4(reviews)

17.2 ms ± 94.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

3. Какая из созданных функций выполняется медленнее? Что наиболее сильно влияет на скорость выполнения? Для ответа использовать профайлер `line_profiler`. Сохраните результаты работы профайлера в отдельную текстовую ячейку и прокомментируйте результаты его работы.

(*). Сможете ли вы ускорить работу функции 2В?

In [28]:
%lprun -f get_mean_rating_of_2010 get_mean_rating_of_2010(reviews)

```
Total time: 48.2732 s
File: <ipython-input-20-1027913cd611>
Function: get_mean_rating_of_2010 at line 2

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     2                                           def get_mean_rating_of_2010(df):
     3         1         21.0     21.0      0.0      acc, cnt = 0, 0
     4    126697  442715768.0   3494.3     91.7      for index, row in df.iterrows():
     5    126696   37306789.0    294.5      7.7          if row['date'].year == 2010:
     6     12094    2573898.0    212.8      0.5              acc += row['rating']
     7     12094     135048.0     11.2      0.0              cnt += 1
     8         1         15.0     15.0      0.0      return acc / cnt
```

In [29]:
%lprun -f get_mean_rating_of_2010_v2 get_mean_rating_of_2010_v2(reviews)

```
Total time: 4.61255 s
File: <ipython-input-20-1027913cd611>
Function: get_mean_rating_of_2010_v2 at line 10

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    10                                           def get_mean_rating_of_2010_v2(df):
    11         1         22.0     22.0      0.0      acc, cnt = 0, 0
    12         1     213800.0 213800.0      0.5      df = df[df['date'].dt.year == 2010]
    13     12095   42209311.0   3489.8     91.5      for index, row in df.iterrows():
    14     12094    3550739.0    293.6      7.7          acc += row['rating']
    15     12094     151627.0     12.5      0.3          cnt += 1
    16         1         17.0     17.0      0.0      return acc / cnt
```

In [30]:
%lprun -f get_mean_rating_of_2010_v3 get_mean_rating_of_2010_v3(reviews)

```
Total time: 0.0386734 s
File: <ipython-input-20-1027913cd611>
Function: get_mean_rating_of_2010_v3 at line 18

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    18                                           def get_mean_rating_of_2010_v3(df):
    19         1     214540.0 214540.0     55.5      rating = df[df['date'].dt.year == 2010]['rating']
    20         1     171932.0 171932.0     44.5      acc = sum(df['rating'])
    21         1        262.0    262.0      0.1      return acc / len(rating)
```

In [31]:
%lprun -f get_mean_rating_of_2010_v4 get_mean_rating_of_2010_v4(reviews)

4. Вам предлагается воспользоваться функцией, которая собирает информацию, сколько отзывов содержат то или иное слово. Измерьте время выполнения этой функции. Сможете ли вы найти узкие места в коде, используя профайлер? Выпишите (словами), что в имеющемся коде реализовано неоптимально. Оптимизируйте функцию и добейтесь значительного прироста в скорости выполнения.

In [10]:
def get_word_reviews_count(df):
    word_reviews = {}
    for _, row in df.dropna(subset=['review']).iterrows():
        recipe_id, review = row['recipe_id'], row['review']
        words = review.split(' ')
        for word in words:
            if word not in word_reviews:
                word_reviews[word] = []
            word_reviews[word].append(recipe_id)
    
    word_reviews_count = {}
    for _, row in df.dropna(subset=['review']).iterrows():
        review = row['review']
        words = review.split(' ')
        for word in words:
            word_reviews_count[word] = len(word_reviews[word])
    return word_reviews_count

In [11]:
def get_word_reviews_count_v2(df):
    from collections import defaultdict
    word_reviews_count = defaultdict(int)
    for _, row in df.dropna(subset=['review']).iterrows():
        review = row['review']
        words = review.split(' ')
        for word in row['review'].split(' '):
            word_reviews_count[word] += 1
    return word_reviews_count

In [17]:
def get_word_reviews_count_v3(df):
    from collections import Counter
    words = reviews['review'].dropna().str.split(' ').explode()
    return Counter(words)

In [52]:
%%time
get_word_reviews_count(reviews);

Wall time: 58 s

{'Last': 94,
 'week': 804,
 'whole': 5628,
 'sides': 312,
 'of': 109029,
 'frozen': 2647,
 'salmon': 729,
 'fillet': 60,
 'was': 88781,
 'on': 34583,
 'sale': 149,
 'in': 61539,
 'my': 44144,
 'local': 561,
 'supermarket,': 10,
 'so': 46090,
 'I': 285147,
 'bought': 1369,
 'tons': 161,
 '(okay,': 5,
 'only': 13965,
 '3,': 48,
 'but': 42513,
 'total': 381,
 'weight': 160,
 'over': 9065,
 '10': 2303,
 'pounds).': 2,
 '': 214145,
 'This': 39448,
 'recipe': 41098,
 'is': 55075,
 'perfect': 4398,
 'for': 121224,
 'fillet,': 14,
 'even': 7878,
 'though': 2314,
 'it': 111175,
 'calls': 520,
 'steaks.': 93,
 'cut': 6688,
 'up': 13585,
 'the': 266050,
 'into': 7031,
 'individual': 314,
 'portions': 156,
 'and': 217849,
 'followed': 4859,
 'instructions': 731,
 'exactly.': 571,
 "I'm": 7145,
 'one': 15086,
 'those': 2287,
 'food': 2413,
 'combining': 74,
 'diets,': 5,
 'left': 4690,
 'out': 23644,
 'white': 3425,
 'wine': 1256,
 'added': 21710,
 'just': 24944,
 'a': 166136,
 'dash': 532,
 'vinegar': 1272,
 'instead': 10395,
 '(just': 273,
 'little': 16319,
 'bit,': 316,
 'not': 22907,
 'enough': 4440,
 'to': 131471,
 'change': 4146,
 'taste': 8026,
 'dish).': 20,
 'Super': 840,
 'yummy,': 366,
 'leftovers': 1497,
 'lunch': 1593,
 'today': 1034,
 '(lucky': 3,
 'me)!': 5,
 'So': 4319,
 'simple': 3947,
 'tasty!': 994,
 'used': 44849,
 'yellow': 782,
 'capsicum': 45,
 'place': 2012,
 'green': 4470,
 'because': 11390,
 "that's": 1563,
 'what': 7462,
 'had': 26362,
 'hand.': 1416,
 'came': 5263,
 'together': 3268,
 'fast.': 178,
 'Perfect': 755,
 'meal': 1891,
 'if': 7326,
 'you': 24475,
 "don't": 6183,
 'have': 35190,
 'lot': 3186,
 'time.': 4010,
 'Easy,': 288,
 'healthy': 1282,
 'tasty.': 1986,
 'Thanks': 26556,
 'Stardustannie!': 4,
 'Made': 12801,
 'PAC': 1488,
 'Fall': 737,
 '2007.': 85,
 'Very': 8691,
 'nice': 8168,
 'breakfast': 1398,
 'HH,': 1,
 'easy': 17222,
 'make': 32124,
 'yummy': 2111,
 'with': 58374,
 'fresh': 7670,
 'hot': 3578,
 'coffe.': 2,
 'Instead': 860,
 'toast': 449,
 'served': 6449,
 '#97694': 1,
 'by': 6592,
 'Paula': 121,
 'G': 13,
 'that': 36984,
 'made': 38087,
 'earlier': 167,
 'turned': 6368,
 'great.': 3686,
 'will': 23985,
 'be': 25032,
 'regular': 2988,
 'our': 6879,
 'house': 1246,
 '-': 12000,
 'DH': 3796,
 'loved': 13755,
 'them.': 3663,
 'These': 8371,
 'are': 15518,
 'favorite': 2587,
 'holidays': 123,
 'children': 356,
 'We': 12585,
 'also': 14466,
 'use': 16905,
 'Rolo': 6,
 'candies': 59,
 'kisses.': 14,
 'Excellent': 1550,
 'soup!': 456,
 'The': 25720,
 'tomato': 2136,
 'flavor': 7690,
 'this': 87057,
 'freezer': 874,
 'tag': 808,
 'soup': 4437,
 'froze': 645,
 'beautifully.': 305,
 'prepared': 935,
 'as': 35493,
 'directed': 720,
 'then': 8440,
 'allowed': 225,
 'cool': 953,
 'container.': 46,
 'thawed': 211,
 'fridge': 922,
 'reheated': 222,
 'stovetop.': 38,
 'Worked': 251,
 'perfectly!': 158,
 'forgot': 1290,
 'add': 12987,
 'skim': 409,
 'milk': 3759,
 'still': 6693,
 'tasted': 4119,
 'pretty': 3499,
 'good!': 3887,
 'Dancer!': 17,
 'dinner': 3882,
 'excellent,': 186,
 'finally': 513,
 'found': 5067,
 'tuna': 488,
 'casserole': 798,
 'we': 12841,
 'enjoy,': 11,
 'thanks.': 123,
 'When': 1630,
 'snapped': 9,
 'picture,': 61,
 'review': 1142,
 'recipe.': 14337,
 'toasted': 775,
 'pecans': 624,
 'dish,': 801,
 'at': 15362,
 'party': 1243,
 'Prime': 23,
 'Rib.': 4,
 'Ten': 16,
 'stars': 2070,
 'Lennie': 29,
 '!!': 334,
 'good': 16106,
 'combination': 1801,
 'flavors': 2212,
 'reduce': 910,
 'rice': 3664,
 'cilantro': 731,
 'next': 10082,
 'time,': 2236,
 'thanks': 3197,
 'sharing': 6196,
 'hon!...Kitten': 9,
 'Oh': 1335,
 'Bergy!': 61,
 'wonderful': 5681,
 'cakes': 433,
 'awesome.': 550,
 'Fast': 83,
 'put': 8578,
 'together.': 1445,
 'get': 6753,
 'fish': 1128,
 'where': 971,
 'live': 435,
 '(yuck).': 5,
 'am': 6191,
 'tired': 147,
 'trying': 1847,
 'new': 2765,
 'recipes': 2819,
 'help': 761,
 'lack': 174,
 'quality.': 62,
 'But': 2588,
 'recipe,': 5129,
 'problem.': 194,
 'did': 17358,
 '3': 4472,
 'cloves': 897,
 'garlic,': 1029,
 'seasoned': 776,
 'bread': 5904,
 'crumbs': 801,
 'Smash': 3,
 'Seasoning(318441).': 1,
 'It': 19417,
 'has': 4861,
 'no': 5863,
 'salt!\r\nI': 1,
 'tartar': 77,
 'sauce': 11425,
 'go': 3691,
 '(56860).\r\nThank': 1,
 'great': 19166,
 'recipe!': 8487,
 'very': 25681,
 'moist': 2457,
 'cornbread,': 47,
 'two': 4466,
 'days': 723,
 'later.': 237,
 'less': 3180,
 'sugar': 6608,
 'honey,': 203,
 'farm': 56,
 'butter...and': 3,
 'corn,': 222,
 'about': 12811,
 '2': 8237,
 'ears.': 5,
 'Served': 1974,
 'ribs': 1203,
 'grill,': 124,
 "I've": 5561,
 'been': 5786,
 'making': 11030,
 'past': 418,
 'several': 1714,
 'years.': 460,
 "It's": 2848,
 'always': 4167,
 'extremely': 598,
 'easy!': 923,
 'posting!': 2469,
 'generic': 30,
 'sweetened': 239,
 'condensed': 231,
 'works': 748,
 'well,': 782,
 'tastes': 2271,
 'costs': 17,
 '(I': 2369,
 'usually': 1911,
 'Wal-Mart': 3,
 'brand).': 9,
 'Exceptional': 7,
 'delicious': 5729,
 'make.': 3027,
 'really': 19400,
 'liked': 5537,
 'weekday': 69,
 'leftover': 1716,
 'rice.': 1105,
 'looking': 3050,
 'different': 3537,
 'ways': 353,
 'ground': 2468,
 'beef.': 346,
 'love': 9526,
 'sandwich!!': 10,
 'alot': 435,
 'sooo': 594,
 'Lite': 22,
 'brown': 3475,
 'mustard': 1082,
 'horse': 4,
 'relish': 159,
 'some': 20753,
 'olives': 582,
 "on's.": 1,
 'Next': 3485,
 'time': 17502,
 'balsamic': 482,
 'dressing...it': 2,
 'mind.': 76,
 ':)': 5164,
 'cbreezie': 1,
 'make,': 1286,
 'affordable': 26,
 'addicting.': 29,
 'Our': 363,
 'household': 66,
 'it.': 11935,
 'Blessings': 7,
 'chef': 292,
 'sharing.': 2159,
 'never': 4979,
 'apple': 1442,
 'orange': 1633,
 'juice': 2765,
 'makes': 3300,
 'all': 15499,
 'difference': 673,
 'texture': 2318,
 'bread.': 1207,
 'wonderful!!\r\nThank': 2,
 'You': 2286,
 'were': 20716,
 'delicious!': 3344,
 'grated': 943,
 'bit': 9946,
 'cheddar': 1380,
 'cheese': 8218,
 'top': 4343,
 '5': 4283,
 'minutes': 5013,
 'before': 6918,
 'they': 16863,
 'done,': 239,
 'seasoning': 2026,
 'perfect.': 2023,
 'best': 4551,
 'pizza': 955,
 'dough': 2740,
 'made!': 190,
 'Other': 574,
 'tried': 4438,
 'machine': 480,
 'way': 6708,
 'too': 10530,
 'sticky.': 81,
 'Leaving': 11,
 'msg': 19,
 'fine.': 946,
 'divide': 60,
 'half,': 411,
 'knead': 90,
 'floured': 83,
 'surface': 69,
 'few': 4897,
 'times,': 290,
 'stretch': 74,
 'cirle.': 1,
 'like': 20171,
 'bake': 1806,
 'cast-iron': 19,
 'skillet-': 1,
 'brush': 161,
 'pan': 3626,
 'olive': 2058,
 'oil': 3790,
 'sprinkle': 635,
 'corn': 2175,
 'meal.': 1607,
 'crust': 1662,
 '7': 705,
 '10-15': 75,
 'lowest': 28,
 'rack': 265,
 'oven.': 1053,
 'saw': 745,
 'Giada': 8,
 'Today': 106,
 'show': 174,
 'last': 4502,
 'month': 270,
 'wanted': 2687,
 'compare': 104,
 'family': 7201,
 'being': 1855,
 'Marsala': 25,
 'dry': 2150,
 'red,': 78,
 'chicken/turkey': 3,
 'sausage,': 225,
 'cutting': 557,
 'sausages': 113,
 'finishing': 127,
 'cooking': 4203,
 'stove': 565,
 'My': 14347,
 'traditionally': 25,
 'serves': 152,
 'sausage': 1116,
 'peppers': 1410,
 'polenta...this': 1,
 'compared': 122,
 'well': 5166,
 'probably': 2651,
 'calories': 377,
 'heats': 11,
 'kitchen': 520,
 'summertime!': 2,
 'meatloaf,': 47,
 'took': 3830,
 'reviewers': 587,
 'suggestion': 524,
 'another': 4777,
 'crock': 1034,
 'pot': 1977,
 'meatloaf': 395,
 '(#99616)': 1,
 'it,': 3813,
 'sauce,': 1640,
 'meatloaf.': 109,
 'sweet': 4938,
 'tangy': 290,
 'wonder': 263,
 'addition.': 273,
 'again.': 7348,
 'deliciously': 87,
 'simple.': 292,
 'can': 9513,
 'literally': 148,
 'thrown': 103,
 'soups': 203,
 'i': 7770,
 'ever': 3856,
 'had.': 886,
 'uncomplicated': 6,
 'taste.': 2042,
 ',': 715,
 'from': 12802,
 'appealed': 20,
 'me': 7274,
 'simplicity': 162,
 'quick': 4068,
 'could': 6285,
 'made.': 705,
 'both': 2697,
 'flavor.': 3912,
 'anything': 1423,
 'see': 2244,
 'can;': 1,
 'more': 16840,
 'substance': 14,
 'nothing': 718,
 '(thankfully)': 3,
 'rustic': 43,
 'roasted': 1256,
 'balance': 423,
 'other': 7016,
 'ingredients.': 1084,
 'paul': 2,
 'newman': 1,
 'marinara': 109,
 '1/3': 778,
 'cup': 7164,
 'let': 2910,
 'simmer': 398,
 'out.': 1223,
 'would': 16597,
 'definitly': 60,
 'much': 12363,
 'plus': 779,
 'tea!': 45,
 'aroma': 300,
 'tea': 535,
 'steeping': 10,
 'five': 663,
 'minutes,': 843,
 'wonderful!': 1109,
 'large': 2093,
 'glass': 571,
 'ice': 1500,
 'enjoyed!': 69,
 'Good': 1325,
 'marinade.': 218,
 'Jack': 169,
 'Daniels': 23,
 'exactly': 3583,
 'except': 2033,
 "didn't": 14046,
 'marinate': 353,
 'quite': 3819,
 'long.': 221,
 'hours.': 867,
 'grilled': 1248,
 'counter': 137,
 'grill': 812,
 'everyone': 2528,
 'enjoyed': 6746,
 'Even': 1366,
 'DH,': 122,
 'who': 3066,
 "doesn't": 1810,
 'beef': 2513,
 'dressed': 64,
 'up,': 513,
 'said': 3122,
 'Almost': 108,
 'teriyaki': 96,
 'baked': 4137,
 'potato': 1754,
 'asparagus.': 143,
 'posting.': 2221,
 'Fantastic': 361,
 'earning': 2,
 'raves': 111,
 'table.': 201,
 'Thanks,': 1331,
 'homegirl!': 5,
 'comforting.': 50,
 'low-sodium,': 1,
 'low-fat': 296,
 'chicken': 11332,
 'stock.': 166,
 'butter.': 945,
 'dried': 2248,
 'parsley.': 200,
 'do': 6861,
 'than': 10333,
 'an': 10553,
 'hour,': 174,
 'Me': 65,
 'course.': 92,
 'Breezermom': 3,
 'Market': 162,
 'game': 469,
 'Easy': 1911,
 'good.': 7001,
 'Will': 3432,
 'again': 7921,
 'kids': 3123,
 'weekend,': 54,
 'your': 6415,
 'cookies': 1935,
 'already': 1564,
 '(your': 4,
 'Triple': 17,
 'Chocolates).': 1,
 "We're": 115,
 'addicted': 63,
 'jam': 430,
 '--': 1634,
 "it's": 4846,
 'tend': 205,
 'vinegar-phobic': 1,
 'half;': 9,
 'adore': 101,
 'black': 1609,
 'pepper,': 929,
 'increase': 507,
 'half.': 567,
 'Also,': 1561,
 'once': 1547,
 'strawberries': 539,
 'cook': 4212,
 'down,': 140,
 'masher': 37,
 'break': 188,
 'them': 19689,
 'consistency.': 287,
 'pepper': 4401,
 'kick': 525,
 'fun,': 59,
 'English': 151,
 'muffins,': 161,
 'peanut': 1356,
 'butter': 5572,
 '&': 9664,
 'jelly': 298,
 'sandwiches': 473,
 '(made': 53,
 'wheat': 1778,
 'bread.)': 3,
 'wish': 831,
 'canning': 142,
 'store': 1248,
 'shelf': 48,
 'it!': 4313,
 'started': 876,
 'yesterday': 436,
 'keep': 2162,
 'up.': 1429,
 'back': 3474,
 'coffee': 976,
 'figured': 251,
 'might': 2834,
 'along': 1572,
 'benefits.': 12,
 'OK,': 118,
 'NEVER': 136,
 'buy': 1174,
 'jarred': 130,
 'terrific!': 129,
 'early': 259,
 'day,': 352,
 'later!': 31,
 'pizza,': 66,
 'freezer.': 284,
 'cant': 183,
 'wait.': 63,
 'hint': 419,
 'spice': 1363,
 'red': 4424,
 'omitted': 1607,
 'flakes': 754,
 'small': 3035,
 'delicious.': 3734,
 'again,': 2053,
 'tenderness': 27,
 'rub': 356,
 'right.': 542,
 'cold,': 101,
 'yogurt': 961,
 'whipped': 834,
 'in,': 275,
 'or': 12020,
 'top.': 1375,
 'cumin,': 184,
 'curry,': 57,
 'cinnamon': 2082,
 'try': 8937,
 'Chinese': 203,
 '5.': 153,
 "can't": 3022,
 'resist': 98,
 'splash': 304,
 'too!': 1288,
 '"bake"': 5,
 'squash': 549,
 'microwave': 830,
 '8': 1712,
 'minute': 545,
 'blasts': 1,
 'peel': 343,
 'when': 9491,
 'cool,': 89,
 'freeze': 792,
 'flesh.': 7,
 'Carrots': 32,
 'eaten': 749,
 'right': 3563,
 'highly': 529,
 'recommend': 1542,
 'these': 14418,
 'delicious,': 1064,
 'yet': 1087,
 'treats!': 27,
 'plastic': 293,
 'popsicle': 9,
 'molds': 10,
 'store.': 239,
 'halved': 1284,
 '16': 340,
 'popsicles.': 5,
 'They': 5927,
 'adults': 195,
 'gone': 759,
 'crazy': 379,
 'eating': 2032,
 'And': 2587,
 'since': 4612,
 "they're": 440,
 'them!': 817,
 'Barb': 33,
 'become': 734,
 'favorite!': 215,
 'good,': 3031,
 'modifications': 131,
 '(and': 1001,
 'laziness).': 1,
 'semi': 81,
 'breasts,': 185,
 'browned': 670,
 'them,': 1125,
 'stock': 853,
 'rest': 1884,
 'through': 1258,
 'simmer.': 28,
 'omit': 595,
 'avoid': 195,
 'sugary-ness': 1,
 'commented': 144,
 'PERFECT.': 35,
 'As': 1547,
 'couscous': 179,
 'anything,': 94,
 'cold': 1240,
 'broth': 1953,
 'soak': 317,
 'wait': 2103,
 'breasts': 981,
 'cook.': 325,
 'margarine': 312,
 'garlic-buttery': 1,
 'certainly': 920,
 'disappoint).': 1,
 '#289161.': 1,
 'Miraklegirl!': 4,
 'fantastic!': 779,
 'soft': 1275,
 'chewy': 397,
 'loveddd': 1,
 'friends.': 197,
 'chopped': 3127,
 'mars': 2,
 'bar': 219,
 'chocolate': 4609,
 'chips': 1692,
 'worked': 3075,
 'charm': 25,
 'definitely': 6267,
 'THANKS': 93,
 'Christmas': 1344,
 'party!': 71,
 'Thank': 9735,
 'treat!': 343,
 'dressing': 2160,
 'lot.': 369,
 'sesame': 650,
 'seeds': 805,
 'lamb': 384,
 'marinaded': 64,
 'spices.': 376,
 'posting': 4351,
 'simply': 738,
 'WONDERFUL!': 102,
 'any': 6231,
 'salt,': 1020,
 'substitution': 119,
 "necessity..didn't": 1,
 'hash': 168,
 'browns,': 19,
 'potatoes.': 996,
 'About': 72,
 'half': 7891,
 'peeked': 5,
 'browning': 302,
 'bottom': 1067,
 'potatoes': 3793,
 "weren't": 511,
 'cooking.': 721,
 'needed': 2633,
 'water.': 897,
 'DUH!': 1,
 'remember': 574,
 'how': 5263,
 'added,': 81,
 "I'll": 5414,
 'redo': 7,
 'browns': 104,
 'die': 409,
 'for....': 2,
 'truly!': 1,
 'good..': 25,
 'it..': 61,
 'give': 3294,
 '3.5': 93,
 'stars.': 688,
 'okay': 242,
 'again.<br/><br/>I': 2,
 'drumsticks': 59,
 'wings': 425,
 'grocery': 438,
 'low': 2407,
 'sodium': 453,
 'soy': 1154,
 'sauce.': 3014,
 'forget': 241,
 'marinade': 1074,
 'chicken.': 1191,
 'know': 3493,
 'affected': 64,
 'thicker.': 86,
 'barbecue': 199,
 'move': 69,
 'fluid.': 6,
 'thicken': 702,
 'starch': 190,
 'flour.': 770,
 'stated': 531,
 ':-)': 651,
 'breakfast!': 170,
 'mom': 793,
 'Northern': 39,
 'Ireland': 14,
 'introduced': 38,
 'Marmite': 9,
 'age': 38,
 'rye': 150,
 'marmite': 8,
 'dip': 1014,
 'eggs.': 408,
 'you!': 1483,
 "Paula's": 14,
 'Peach': 20,
 'Dump': 9,
 'Cake': 198,
 '#125391': 1,
 '(only': 110,
 '4)': 28,
 'forward': 785,
 'her': 1377,
 'call': 572,
 'future.': 285,
 'hand': 1526,
 'dessert': 1009,
 "'fix'": 2,
 'table': 454,
 'short': 442,
 'notice.': 16,
 'Wow!': 684,
 'What': 2588,
 'amazing': 894,
 'stuff!': 202,
 'Hokey': 4,
 'Pokey': 5,
 'ice-cream,': 6,
 'this.\nI': 3,
 'shocked': 59,
 'complete': 234,
 'colour': 105,
 'after': 5685,
 'stirring': 211,
 'baking': 3090,
 'soda': 304,
 'through.': 295,
 'quick.\nI': 1,
 'burned': 183,
 'ours': 252,
 'difficult': 371,
 'spread': 1079,
 'flat': 296,
 'pan,': 648,
 'first': 6060,
 'go.\nNext': 1,
 "what's": 98,
 'come!': 37,
 'manual': 7,
 'method': 625,
 'directions': 1514,
 'follow': 830,
 'produced': 149,
 'results.': 577,
 'light': 2557,
 "za'atar": 11,
 'topping.': 466,
 'keeper!': 1322,
 'Best': 634,
 '2011': 181,
 'event,': 33,
 'recommended': 325,
 'awalde': 7,
 'sorry.': 81,
 "wasn't": 2828,
 'stretch.': 6,
 'There': 1134,
 'something': 3789,
 'missing': 501,
 'turn': 1174,
 'amazing.': 614,
 'turmeric': 68,
 'strange': 126,
 'color': 571,
 'unappealing.': 7,
 'smelled': 705,
 'carne': 7,
 'asada': 5,
 'maybe': 2146,
 'expecting.': 53,
 'cooked': 6317,
 'delightful': 259,
 'while': 3129,
 'grilling': 225,
 'meet': 53,
 'expectations': 42,
 'served.': 66,
 'watching': 228,
 'think': 10740,
 'tweak': 194,
 'sure': 5334,
 'is.': 636,
 'Did': 453,
 'Bergy!!': 10,
 'microwaved': 176,
 'spuds,': 5,
 'onions,': 735,
 'later': 496,
 'night.': 694,
 'onion': 3951,
 'each': 2204,
 'their': 1558,
 'flavours': 430,
 'come': 1545,
 'distinctly.\r\nGood': 1,
 'veggie': 655,
 'dish.': 2670,
 'Lovely!': 31,
 'beautiful': 760,
 'Thanksgiving': 638,
 'morning.': 386,
 'With': 666,
 'link': 42,
 'sliced': 2056,
 'fruit': 1048,
 'enjoy': 1321,
 'visiting': 112,
 'grands': 5,
 'breakfast.': 477,
 'Kittencal.': 81,
 'teach': 25,
 'high': 1257,
 'school': 333,
 'foods': 180,
 'class': 97,
 'studying': 8,
 'legumes.': 2,
 'topping': 1361,
 'sour': 2563,
 'cream,': 790,
 'cheese,': 1367,
 'Tobasco': 19,
 'tortilla': 507,
 'chips.': 630,
 'While': 418,
 'making,': 33,
 'students': 37,
 'look': 1527,
 'Not': 1846,
 'single': 364,
 'student': 38,
 '25': 458,
 'disliked': 19,
 'students.': 8,
 'starting': 247,
 'hour': 1180,
 'period': 41,
 'reheating': 45,
 'day.': 1214,
 'Many': 181,
 'requested': 363,
 'second': 1653,
 'copy': 147,
 'take': 2301,
 'home!': 96,
 'Great': 5595,
 'job!': 33,
 'definately': 1072,
 'lemon': 3806,
 'zest': 575,
 'devine': 17,
 'reheat': 135,
 'oven': 3332,
 ...}

In [12]:
%%time
get_word_reviews_count_v2(reviews);

Wall time: 31.1 s

defaultdict(int,
            {'Last': 94,
             'week': 804,
             'whole': 5628,
             'sides': 312,
             'of': 109029,
             'frozen': 2647,
             'salmon': 729,
             'fillet': 60,
             'was': 88781,
             'on': 34583,
             'sale': 149,
             'in': 61539,
             'my': 44144,
             'local': 561,
             'supermarket,': 10,
             'so': 46090,
             'I': 285147,
             'bought': 1369,
             'tons': 161,
             '(okay,': 5,
             'only': 13965,
             '3,': 48,
             'but': 42513,
             'total': 381,
             'weight': 160,
             'over': 9065,
             '10': 2303,
             'pounds).': 2,
             '': 214145,
             'This': 39448,
             'recipe': 41098,
             'is': 55075,
             'perfect': 4398,
             'for': 121224,
             'fillet,': 14,
             'even': 7878,
             'though': 2314,
             'it': 111175,
             'calls': 520,
             'steaks.': 93,
             'cut': 6688,
             'up': 13585,
             'the': 266050,
             'into': 7031,
             'individual': 314,
             'portions': 156,
             'and': 217849,
             'followed': 4859,
             'instructions': 731,
             'exactly.': 571,
             "I'm": 7145,
             'one': 15086,
             'those': 2287,
             'food': 2413,
             'combining': 74,
             'diets,': 5,
             'left': 4690,
             'out': 23644,
             'white': 3425,
             'wine': 1256,
             'added': 21710,
             'just': 24944,
             'a': 166136,
             'dash': 532,
             'vinegar': 1272,
             'instead': 10395,
             '(just': 273,
             'little': 16319,
             'bit,': 316,
             'not': 22907,
             'enough': 4440,
             'to': 131471,
             'change': 4146,
             'taste': 8026,
             'dish).': 20,
             'Super': 840,
             'yummy,': 366,
             'leftovers': 1497,
             'lunch': 1593,
             'today': 1034,
             '(lucky': 3,
             'me)!': 5,
             'So': 4319,
             'simple': 3947,
             'tasty!': 994,
             'used': 44849,
             'yellow': 782,
             'capsicum': 45,
             'place': 2012,
             'green': 4470,
             'because': 11390,
             "that's": 1563,
             'what': 7462,
             'had': 26362,
             'hand.': 1416,
             'came': 5263,
             'together': 3268,
             'fast.': 178,
             'Perfect': 755,
             'meal': 1891,
             'if': 7326,
             'you': 24475,
             "don't": 6183,
             'have': 35190,
             'lot': 3186,
             'time.': 4010,
             'Easy,': 288,
             'healthy': 1282,
             'tasty.': 1986,
             'Thanks': 26556,
             'Stardustannie!': 4,
             'Made': 12801,
             'PAC': 1488,
             'Fall': 737,
             '2007.': 85,
             'Very': 8691,
             'nice': 8168,
             'breakfast': 1398,
             'HH,': 1,
             'easy': 17222,
             'make': 32124,
             'yummy': 2111,
             'with': 58374,
             'fresh': 7670,
             'hot': 3578,
             'coffe.': 2,
             'Instead': 860,
             'toast': 449,
             'served': 6449,
             '#97694': 1,
             'by': 6592,
             'Paula': 121,
             'G': 13,
             'that': 36984,
             'made': 38087,
             'earlier': 167,
             'turned': 6368,
             'great.': 3686,
             'will': 23985,
             'be': 25032,
             'regular': 2988,
             'our': 6879,
             'house': 1246,
             '-': 12000,
             'DH': 3796,
             'loved': 13755,
             'them.': 3663,
             'These': 8371,
             'are': 15518,
             'favorite': 2587,
             'holidays': 123,
             'children': 356,
             'We': 12585,
             'also': 14466,
             'use': 16905,
             'Rolo': 6,
             'candies': 59,
             'kisses.': 14,
             'Excellent': 1550,
             'soup!': 456,
             'The': 25720,
             'tomato': 2136,
             'flavor': 7690,
             'this': 87057,
             'freezer': 874,
             'tag': 808,
             'soup': 4437,
             'froze': 645,
             'beautifully.': 305,
             'prepared': 935,
             'as': 35493,
             'directed': 720,
             'then': 8440,
             'allowed': 225,
             'cool': 953,
             'container.': 46,
             'thawed': 211,
             'fridge': 922,
             'reheated': 222,
             'stovetop.': 38,
             'Worked': 251,
             'perfectly!': 158,
             'forgot': 1290,
             'add': 12987,
             'skim': 409,
             'milk': 3759,
             'still': 6693,
             'tasted': 4119,
             'pretty': 3499,
             'good!': 3887,
             'Dancer!': 17,
             'dinner': 3882,
             'excellent,': 186,
             'finally': 513,
             'found': 5067,
             'tuna': 488,
             'casserole': 798,
             'we': 12841,
             'enjoy,': 11,
             'thanks.': 123,
             'When': 1630,
             'snapped': 9,
             'picture,': 61,
             'review': 1142,
             'recipe.': 14337,
             'toasted': 775,
             'pecans': 624,
             'dish,': 801,
             'at': 15362,
             'party': 1243,
             'Prime': 23,
             'Rib.': 4,
             'Ten': 16,
             'stars': 2070,
             'Lennie': 29,
             '!!': 334,
             'good': 16106,
             'combination': 1801,
             'flavors': 2212,
             'reduce': 910,
             'rice': 3664,
             'cilantro': 731,
             'next': 10082,
             'time,': 2236,
             'thanks': 3197,
             'sharing': 6196,
             'hon!...Kitten': 9,
             'Oh': 1335,
             'Bergy!': 61,
             'wonderful': 5681,
             'cakes': 433,
             'awesome.': 550,
             'Fast': 83,
             'put': 8578,
             'together.': 1445,
             'get': 6753,
             'fish': 1128,
             'where': 971,
             'live': 435,
             '(yuck).': 5,
             'am': 6191,
             'tired': 147,
             'trying': 1847,
             'new': 2765,
             'recipes': 2819,
             'help': 761,
             'lack': 174,
             'quality.': 62,
             'But': 2588,
             'recipe,': 5129,
             'problem.': 194,
             'did': 17358,
             '3': 4472,
             'cloves': 897,
             'garlic,': 1029,
             'seasoned': 776,
             'bread': 5904,
             'crumbs': 801,
             'Smash': 3,
             'Seasoning(318441).': 1,
             'It': 19417,
             'has': 4861,
             'no': 5863,
             'salt!\r\nI': 1,
             'tartar': 77,
             'sauce': 11425,
             'go': 3691,
             '(56860).\r\nThank': 1,
             'great': 19166,
             'recipe!': 8487,
             'very': 25681,
             'moist': 2457,
             'cornbread,': 47,
             'two': 4466,
             'days': 723,
             'later.': 237,
             'less': 3180,
             'sugar': 6608,
             'honey,': 203,
             'farm': 56,
             'butter...and': 3,
             'corn,': 222,
             'about': 12811,
             '2': 8237,
             'ears.': 5,
             'Served': 1974,
             'ribs': 1203,
             'grill,': 124,
             "I've": 5561,
             'been': 5786,
             'making': 11030,
             'past': 418,
             'several': 1714,
             'years.': 460,
             "It's": 2848,
             'always': 4167,
             'extremely': 598,
             'easy!': 923,
             'posting!': 2469,
             'generic': 30,
             'sweetened': 239,
             'condensed': 231,
             'works': 748,
             'well,': 782,
             'tastes': 2271,
             'costs': 17,
             '(I': 2369,
             'usually': 1911,
             'Wal-Mart': 3,
             'brand).': 9,
             'Exceptional': 7,
             'delicious': 5729,
             'make.': 3027,
             'really': 19400,
             'liked': 5537,
             'weekday': 69,
             'leftover': 1716,
             'rice.': 1105,
             'looking': 3050,
             'different': 3537,
             'ways': 353,
             'ground': 2468,
             'beef.': 346,
             'love': 9526,
             'sandwich!!': 10,
             'alot': 435,
             'sooo': 594,
             'Lite': 22,
             'brown': 3475,
             'mustard': 1082,
             'horse': 4,
             'relish': 159,
             'some': 20753,
             'olives': 582,
             "on's.": 1,
             'Next': 3485,
             'time': 17502,
             'balsamic': 482,
             'dressing...it': 2,
             'mind.': 76,
             ':)': 5164,
             'cbreezie': 1,
             'make,': 1286,
             'affordable': 26,
             'addicting.': 29,
             'Our': 363,
             'household': 66,
             'it.': 11935,
             'Blessings': 7,
             'chef': 292,
             'sharing.': 2159,
             'never': 4979,
             'apple': 1442,
             'orange': 1633,
             'juice': 2765,
             'makes': 3300,
             'all': 15499,
             'difference': 673,
             'texture': 2318,
             'bread.': 1207,
             'wonderful!!\r\nThank': 2,
             'You': 2286,
             'were': 20716,
             'delicious!': 3344,
             'grated': 943,
             'bit': 9946,
             'cheddar': 1380,
             'cheese': 8218,
             'top': 4343,
             '5': 4283,
             'minutes': 5013,
             'before': 6918,
             'they': 16863,
             'done,': 239,
             'seasoning': 2026,
             'perfect.': 2023,
             'best': 4551,
             'pizza': 955,
             'dough': 2740,
             'made!': 190,
             'Other': 574,
             'tried': 4438,
             'machine': 480,
             'way': 6708,
             'too': 10530,
             'sticky.': 81,
             'Leaving': 11,
             'msg': 19,
             'fine.': 946,
             'divide': 60,
             'half,': 411,
             'knead': 90,
             'floured': 83,
             'surface': 69,
             'few': 4897,
             'times,': 290,
             'stretch': 74,
             'cirle.': 1,
             'like': 20171,
             'bake': 1806,
             'cast-iron': 19,
             'skillet-': 1,
             'brush': 161,
             'pan': 3626,
             'olive': 2058,
             'oil': 3790,
             'sprinkle': 635,
             'corn': 2175,
             'meal.': 1607,
             'crust': 1662,
             '7': 705,
             '10-15': 75,
             'lowest': 28,
             'rack': 265,
             'oven.': 1053,
             'saw': 745,
             'Giada': 8,
             'Today': 106,
             'show': 174,
             'last': 4502,
             'month': 270,
             'wanted': 2687,
             'compare': 104,
             'family': 7201,
             'being': 1855,
             'Marsala': 25,
             'dry': 2150,
             'red,': 78,
             'chicken/turkey': 3,
             'sausage,': 225,
             'cutting': 557,
             'sausages': 113,
             'finishing': 127,
             'cooking': 4203,
             'stove': 565,
             'My': 14347,
             'traditionally': 25,
             'serves': 152,
             'sausage': 1116,
             'peppers': 1410,
             'polenta...this': 1,
             'compared': 122,
             'well': 5166,
             'probably': 2651,
             'calories': 377,
             'heats': 11,
             'kitchen': 520,
             'summertime!': 2,
             'meatloaf,': 47,
             'took': 3830,
             'reviewers': 587,
             'suggestion': 524,
             'another': 4777,
             'crock': 1034,
             'pot': 1977,
             'meatloaf': 395,
             '(#99616)': 1,
             'it,': 3813,
             'sauce,': 1640,
             'meatloaf.': 109,
             'sweet': 4938,
             'tangy': 290,
             'wonder': 263,
             'addition.': 273,
             'again.': 7348,
             'deliciously': 87,
             'simple.': 292,
             'can': 9513,
             'literally': 148,
             'thrown': 103,
             'soups': 203,
             'i': 7770,
             'ever': 3856,
             'had.': 886,
             'uncomplicated': 6,
             'taste.': 2042,
             ',': 715,
             'from': 12802,
             'appealed': 20,
             'me': 7274,
             'simplicity': 162,
             'quick': 4068,
             'could': 6285,
             'made.': 705,
             'both': 2697,
             'flavor.': 3912,
             'anything': 1423,
             'see': 2244,
             'can;': 1,
             'more': 16840,
             'substance': 14,
             'nothing': 718,
             '(thankfully)': 3,
             'rustic': 43,
             'roasted': 1256,
             'balance': 423,
             'other': 7016,
             'ingredients.': 1084,
             'paul': 2,
             'newman': 1,
             'marinara': 109,
             '1/3': 778,
             'cup': 7164,
             'let': 2910,
             'simmer': 398,
             'out.': 1223,
             'would': 16597,
             'definitly': 60,
             'much': 12363,
             'plus': 779,
             'tea!': 45,
             'aroma': 300,
             'tea': 535,
             'steeping': 10,
             'five': 663,
             'minutes,': 843,
             'wonderful!': 1109,
             'large': 2093,
             'glass': 571,
             'ice': 1500,
             'enjoyed!': 69,
             'Good': 1325,
             'marinade.': 218,
             'Jack': 169,
             'Daniels': 23,
             'exactly': 3583,
             'except': 2033,
             "didn't": 14046,
             'marinate': 353,
             'quite': 3819,
             'long.': 221,
             'hours.': 867,
             'grilled': 1248,
             'counter': 137,
             'grill': 812,
             'everyone': 2528,
             'enjoyed': 6746,
             'Even': 1366,
             'DH,': 122,
             'who': 3066,
             "doesn't": 1810,
             'beef': 2513,
             'dressed': 64,
             'up,': 513,
             'said': 3122,
             'Almost': 108,
             'teriyaki': 96,
             'baked': 4137,
             'potato': 1754,
             'asparagus.': 143,
             'posting.': 2221,
             'Fantastic': 361,
             'earning': 2,
             'raves': 111,
             'table.': 201,
             'Thanks,': 1331,
             'homegirl!': 5,
             'comforting.': 50,
             'low-sodium,': 1,
             'low-fat': 296,
             'chicken': 11332,
             'stock.': 166,
             'butter.': 945,
             'dried': 2248,
             'parsley.': 200,
             'do': 6861,
             'than': 10333,
             'an': 10553,
             'hour,': 174,
             'Me': 65,
             'course.': 92,
             'Breezermom': 3,
             'Market': 162,
             'game': 469,
             'Easy': 1911,
             'good.': 7001,
             'Will': 3432,
             'again': 7921,
             'kids': 3123,
             'weekend,': 54,
             'your': 6415,
             'cookies': 1935,
             'already': 1564,
             '(your': 4,
             'Triple': 17,
             'Chocolates).': 1,
             "We're": 115,
             'addicted': 63,
             'jam': 430,
             '--': 1634,
             "it's": 4846,
             'tend': 205,
             'vinegar-phobic': 1,
             'half;': 9,
             'adore': 101,
             'black': 1609,
             'pepper,': 929,
             'increase': 507,
             'half.': 567,
             'Also,': 1561,
             'once': 1547,
             'strawberries': 539,
             'cook': 4212,
             'down,': 140,
             'masher': 37,
             'break': 188,
             'them': 19689,
             'consistency.': 287,
             'pepper': 4401,
             'kick': 525,
             'fun,': 59,
             'English': 151,
             'muffins,': 161,
             'peanut': 1356,
             'butter': 5572,
             '&': 9664,
             'jelly': 298,
             'sandwiches': 473,
             '(made': 53,
             'wheat': 1778,
             'bread.)': 3,
             'wish': 831,
             'canning': 142,
             'store': 1248,
             'shelf': 48,
             'it!': 4313,
             'started': 876,
             'yesterday': 436,
             'keep': 2162,
             'up.': 1429,
             'back': 3474,
             'coffee': 976,
             'figured': 251,
             'might': 2834,
             'along': 1572,
             'benefits.': 12,
             'OK,': 118,
             'NEVER': 136,
             'buy': 1174,
             'jarred': 130,
             'terrific!': 129,
             'early': 259,
             'day,': 352,
             'later!': 31,
             'pizza,': 66,
             'freezer.': 284,
             'cant': 183,
             'wait.': 63,
             'hint': 419,
             'spice': 1363,
             'red': 4424,
             'omitted': 1607,
             'flakes': 754,
             'small': 3035,
             'delicious.': 3734,
             'again,': 2053,
             'tenderness': 27,
             'rub': 356,
             'right.': 542,
             'cold,': 101,
             'yogurt': 961,
             'whipped': 834,
             'in,': 275,
             'or': 12020,
             'top.': 1375,
             'cumin,': 184,
             'curry,': 57,
             'cinnamon': 2082,
             'try': 8937,
             'Chinese': 203,
             '5.': 153,
             "can't": 3022,
             'resist': 98,
             'splash': 304,
             'too!': 1288,
             '"bake"': 5,
             'squash': 549,
             'microwave': 830,
             '8': 1712,
             'minute': 545,
             'blasts': 1,
             'peel': 343,
             'when': 9491,
             'cool,': 89,
             'freeze': 792,
             'flesh.': 7,
             'Carrots': 32,
             'eaten': 749,
             'right': 3563,
             'highly': 529,
             'recommend': 1542,
             'these': 14418,
             'delicious,': 1064,
             'yet': 1087,
             'treats!': 27,
             'plastic': 293,
             'popsicle': 9,
             'molds': 10,
             'store.': 239,
             'halved': 1284,
             '16': 340,
             'popsicles.': 5,
             'They': 5927,
             'adults': 195,
             'gone': 759,
             'crazy': 379,
             'eating': 2032,
             'And': 2587,
             'since': 4612,
             "they're": 440,
             'them!': 817,
             'Barb': 33,
             'become': 734,

In [18]:
%%time
get_word_reviews_count_v3(reviews);

Wall time: 4.51 s

Counter({'Last': 94,
         'week': 804,
         'whole': 5628,
         'sides': 312,
         'of': 109029,
         'frozen': 2647,
         'salmon': 729,
         'fillet': 60,
         'was': 88781,
         'on': 34583,
         'sale': 149,
         'in': 61539,
         'my': 44144,
         'local': 561,
         'supermarket,': 10,
         'so': 46090,
         'I': 285147,
         'bought': 1369,
         'tons': 161,
         '(okay,': 5,
         'only': 13965,
         '3,': 48,
         'but': 42513,
         'total': 381,
         'weight': 160,
         'over': 9065,
         '10': 2303,
         'pounds).': 2,
         '': 214145,
         'This': 39448,
         'recipe': 41098,
         'is': 55075,
         'perfect': 4398,
         'for': 121224,
         'fillet,': 14,
         'even': 7878,
         'though': 2314,
         'it': 111175,
         'calls': 520,
         'steaks.': 93,
         'cut': 6688,
         'up': 13585,
         'the': 266050,
         'into': 7031,
         'individual': 314,
         'portions': 156,
         'and': 217849,
         'followed': 4859,
         'instructions': 731,
         'exactly.': 571,
         "I'm": 7145,
         'one': 15086,
         'those': 2287,
         'food': 2413,
         'combining': 74,
         'diets,': 5,
         'left': 4690,
         'out': 23644,
         'white': 3425,
         'wine': 1256,
         'added': 21710,
         'just': 24944,
         'a': 166136,
         'dash': 532,
         'vinegar': 1272,
         'instead': 10395,
         '(just': 273,
         'little': 16319,
         'bit,': 316,
         'not': 22907,
         'enough': 4440,
         'to': 131471,
         'change': 4146,
         'taste': 8026,
         'dish).': 20,
         'Super': 840,
         'yummy,': 366,
         'leftovers': 1497,
         'lunch': 1593,
         'today': 1034,
         '(lucky': 3,
         'me)!': 5,
         'So': 4319,
         'simple': 3947,
         'tasty!': 994,
         'used': 44849,
         'yellow': 782,
         'capsicum': 45,
         'place': 2012,
         'green': 4470,
         'because': 11390,
         "that's": 1563,
         'what': 7462,
         'had': 26362,
         'hand.': 1416,
         'came': 5263,
         'together': 3268,
         'fast.': 178,
         'Perfect': 755,
         'meal': 1891,
         'if': 7326,
         'you': 24475,
         "don't": 6183,
         'have': 35190,
         'lot': 3186,
         'time.': 4010,
         'Easy,': 288,
         'healthy': 1282,
         'tasty.': 1986,
         'Thanks': 26556,
         'Stardustannie!': 4,
         'Made': 12801,
         'PAC': 1488,
         'Fall': 737,
         '2007.': 85,
         'Very': 8691,
         'nice': 8168,
         'breakfast': 1398,
         'HH,': 1,
         'easy': 17222,
         'make': 32124,
         'yummy': 2111,
         'with': 58374,
         'fresh': 7670,
         'hot': 3578,
         'coffe.': 2,
         'Instead': 860,
         'toast': 449,
         'served': 6449,
         '#97694': 1,
         'by': 6592,
         'Paula': 121,
         'G': 13,
         'that': 36984,
         'made': 38087,
         'earlier': 167,
         'turned': 6368,
         'great.': 3686,
         'will': 23985,
         'be': 25032,
         'regular': 2988,
         'our': 6879,
         'house': 1246,
         '-': 12000,
         'DH': 3796,
         'loved': 13755,
         'them.': 3663,
         'These': 8371,
         'are': 15518,
         'favorite': 2587,
         'holidays': 123,
         'children': 356,
         'We': 12585,
         'also': 14466,
         'use': 16905,
         'Rolo': 6,
         'candies': 59,
         'kisses.': 14,
         'Excellent': 1550,
         'soup!': 456,
         'The': 25720,
         'tomato': 2136,
         'flavor': 7690,
         'this': 87057,
         'freezer': 874,
         'tag': 808,
         'soup': 4437,
         'froze': 645,
         'beautifully.': 305,
         'prepared': 935,
         'as': 35493,
         'directed': 720,
         'then': 8440,
         'allowed': 225,
         'cool': 953,
         'container.': 46,
         'thawed': 211,
         'fridge': 922,
         'reheated': 222,
         'stovetop.': 38,
         'Worked': 251,
         'perfectly!': 158,
         'forgot': 1290,
         'add': 12987,
         'skim': 409,
         'milk': 3759,
         'still': 6693,
         'tasted': 4119,
         'pretty': 3499,
         'good!': 3887,
         'Dancer!': 17,
         'dinner': 3882,
         'excellent,': 186,
         'finally': 513,
         'found': 5067,
         'tuna': 488,
         'casserole': 798,
         'we': 12841,
         'enjoy,': 11,
         'thanks.': 123,
         'When': 1630,
         'snapped': 9,
         'picture,': 61,
         'review': 1142,
         'recipe.': 14337,
         'toasted': 775,
         'pecans': 624,
         'dish,': 801,
         'at': 15362,
         'party': 1243,
         'Prime': 23,
         'Rib.': 4,
         'Ten': 16,
         'stars': 2070,
         'Lennie': 29,
         '!!': 334,
         'good': 16106,
         'combination': 1801,
         'flavors': 2212,
         'reduce': 910,
         'rice': 3664,
         'cilantro': 731,
         'next': 10082,
         'time,': 2236,
         'thanks': 3197,
         'sharing': 6196,
         'hon!...Kitten': 9,
         'Oh': 1335,
         'Bergy!': 61,
         'wonderful': 5681,
         'cakes': 433,
         'awesome.': 550,
         'Fast': 83,
         'put': 8578,
         'together.': 1445,
         'get': 6753,
         'fish': 1128,
         'where': 971,
         'live': 435,
         '(yuck).': 5,
         'am': 6191,
         'tired': 147,
         'trying': 1847,
         'new': 2765,
         'recipes': 2819,
         'help': 761,
         'lack': 174,
         'quality.': 62,
         'But': 2588,
         'recipe,': 5129,
         'problem.': 194,
         'did': 17358,
         '3': 4472,
         'cloves': 897,
         'garlic,': 1029,
         'seasoned': 776,
         'bread': 5904,
         'crumbs': 801,
         'Smash': 3,
         'Seasoning(318441).': 1,
         'It': 19417,
         'has': 4861,
         'no': 5863,
         'salt!\r\nI': 1,
         'tartar': 77,
         'sauce': 11425,
         'go': 3691,
         '(56860).\r\nThank': 1,
         'great': 19166,
         'recipe!': 8487,
         'very': 25681,
         'moist': 2457,
         'cornbread,': 47,
         'two': 4466,
         'days': 723,
         'later.': 237,
         'less': 3180,
         'sugar': 6608,
         'honey,': 203,
         'farm': 56,
         'butter...and': 3,
         'corn,': 222,
         'about': 12811,
         '2': 8237,
         'ears.': 5,
         'Served': 1974,
         'ribs': 1203,
         'grill,': 124,
         "I've": 5561,
         'been': 5786,
         'making': 11030,
         'past': 418,
         'several': 1714,
         'years.': 460,
         "It's": 2848,
         'always': 4167,
         'extremely': 598,
         'easy!': 923,
         'posting!': 2469,
         'generic': 30,
         'sweetened': 239,
         'condensed': 231,
         'works': 748,
         'well,': 782,
         'tastes': 2271,
         'costs': 17,
         '(I': 2369,
         'usually': 1911,
         'Wal-Mart': 3,
         'brand).': 9,
         'Exceptional': 7,
         'delicious': 5729,
         'make.': 3027,
         'really': 19400,
         'liked': 5537,
         'weekday': 69,
         'leftover': 1716,
         'rice.': 1105,
         'looking': 3050,
         'different': 3537,
         'ways': 353,
         'ground': 2468,
         'beef.': 346,
         'love': 9526,
         'sandwich!!': 10,
         'alot': 435,
         'sooo': 594,
         'Lite': 22,
         'brown': 3475,
         'mustard': 1082,
         'horse': 4,
         'relish': 159,
         'some': 20753,
         'olives': 582,
         "on's.": 1,
         'Next': 3485,
         'time': 17502,
         'balsamic': 482,
         'dressing...it': 2,
         'mind.': 76,
         ':)': 5164,
         'cbreezie': 1,
         'make,': 1286,
         'affordable': 26,
         'addicting.': 29,
         'Our': 363,
         'household': 66,
         'it.': 11935,
         'Blessings': 7,
         'chef': 292,
         'sharing.': 2159,
         'never': 4979,
         'apple': 1442,
         'orange': 1633,
         'juice': 2765,
         'makes': 3300,
         'all': 15499,
         'difference': 673,
         'texture': 2318,
         'bread.': 1207,
         'wonderful!!\r\nThank': 2,
         'You': 2286,
         'were': 20716,
         'delicious!': 3344,
         'grated': 943,
         'bit': 9946,
         'cheddar': 1380,
         'cheese': 8218,
         'top': 4343,
         '5': 4283,
         'minutes': 5013,
         'before': 6918,
         'they': 16863,
         'done,': 239,
         'seasoning': 2026,
         'perfect.': 2023,
         'best': 4551,
         'pizza': 955,
         'dough': 2740,
         'made!': 190,
         'Other': 574,
         'tried': 4438,
         'machine': 480,
         'way': 6708,
         'too': 10530,
         'sticky.': 81,
         'Leaving': 11,
         'msg': 19,
         'fine.': 946,
         'divide': 60,
         'half,': 411,
         'knead': 90,
         'floured': 83,
         'surface': 69,
         'few': 4897,
         'times,': 290,
         'stretch': 74,
         'cirle.': 1,
         'like': 20171,
         'bake': 1806,
         'cast-iron': 19,
         'skillet-': 1,
         'brush': 161,
         'pan': 3626,
         'olive': 2058,
         'oil': 3790,
         'sprinkle': 635,
         'corn': 2175,
         'meal.': 1607,
         'crust': 1662,
         '7': 705,
         '10-15': 75,
         'lowest': 28,
         'rack': 265,
         'oven.': 1053,
         'saw': 745,
         'Giada': 8,
         'Today': 106,
         'show': 174,
         'last': 4502,
         'month': 270,
         'wanted': 2687,
         'compare': 104,
         'family': 7201,
         'being': 1855,
         'Marsala': 25,
         'dry': 2150,
         'red,': 78,
         'chicken/turkey': 3,
         'sausage,': 225,
         'cutting': 557,
         'sausages': 113,
         'finishing': 127,
         'cooking': 4203,
         'stove': 565,
         'My': 14347,
         'traditionally': 25,
         'serves': 152,
         'sausage': 1116,
         'peppers': 1410,
         'polenta...this': 1,
         'compared': 122,
         'well': 5166,
         'probably': 2651,
         'calories': 377,
         'heats': 11,
         'kitchen': 520,
         'summertime!': 2,
         'meatloaf,': 47,
         'took': 3830,
         'reviewers': 587,
         'suggestion': 524,
         'another': 4777,
         'crock': 1034,
         'pot': 1977,
         'meatloaf': 395,
         '(#99616)': 1,
         'it,': 3813,
         'sauce,': 1640,
         'meatloaf.': 109,
         'sweet': 4938,
         'tangy': 290,
         'wonder': 263,
         'addition.': 273,
         'again.': 7348,
         'deliciously': 87,
         'simple.': 292,
         'can': 9513,
         'literally': 148,
         'thrown': 103,
         'soups': 203,
         'i': 7770,
         'ever': 3856,
         'had.': 886,
         'uncomplicated': 6,
         'taste.': 2042,
         ',': 715,
         'from': 12802,
         'appealed': 20,
         'me': 7274,
         'simplicity': 162,
         'quick': 4068,
         'could': 6285,
         'made.': 705,
         'both': 2697,
         'flavor.': 3912,
         'anything': 1423,
         'see': 2244,
         'can;': 1,
         'more': 16840,
         'substance': 14,
         'nothing': 718,
         '(thankfully)': 3,
         'rustic': 43,
         'roasted': 1256,
         'balance': 423,
         'other': 7016,
         'ingredients.': 1084,
         'paul': 2,
         'newman': 1,
         'marinara': 109,
         '1/3': 778,
         'cup': 7164,
         'let': 2910,
         'simmer': 398,
         'out.': 1223,
         'would': 16597,
         'definitly': 60,
         'much': 12363,
         'plus': 779,
         'tea!': 45,
         'aroma': 300,
         'tea': 535,
         'steeping': 10,
         'five': 663,
         'minutes,': 843,
         'wonderful!': 1109,
         'large': 2093,
         'glass': 571,
         'ice': 1500,
         'enjoyed!': 69,
         'Good': 1325,
         'marinade.': 218,
         'Jack': 169,
         'Daniels': 23,
         'exactly': 3583,
         'except': 2033,
         "didn't": 14046,
         'marinate': 353,
         'quite': 3819,
         'long.': 221,
         'hours.': 867,
         'grilled': 1248,
         'counter': 137,
         'grill': 812,
         'everyone': 2528,
         'enjoyed': 6746,
         'Even': 1366,
         'DH,': 122,
         'who': 3066,
         "doesn't": 1810,
         'beef': 2513,
         'dressed': 64,
         'up,': 513,
         'said': 3122,
         'Almost': 108,
         'teriyaki': 96,
         'baked': 4137,
         'potato': 1754,
         'asparagus.': 143,
         'posting.': 2221,
         'Fantastic': 361,
         'earning': 2,
         'raves': 111,
         'table.': 201,
         'Thanks,': 1331,
         'homegirl!': 5,
         'comforting.': 50,
         'low-sodium,': 1,
         'low-fat': 296,
         'chicken': 11332,
         'stock.': 166,
         'butter.': 945,
         'dried': 2248,
         'parsley.': 200,
         'do': 6861,
         'than': 10333,
         'an': 10553,
         'hour,': 174,
         'Me': 65,
         'course.': 92,
         'Breezermom': 3,
         'Market': 162,
         'game': 469,
         'Easy': 1911,
         'good.': 7001,
         'Will': 3432,
         'again': 7921,
         'kids': 3123,
         'weekend,': 54,
         'your': 6415,
         'cookies': 1935,
         'already': 1564,
         '(your': 4,
         'Triple': 17,
         'Chocolates).': 1,
         "We're": 115,
         'addicted': 63,
         'jam': 430,
         '--': 1634,
         "it's": 4846,
         'tend': 205,
         'vinegar-phobic': 1,
         'half;': 9,
         'adore': 101,
         'black': 1609,
         'pepper,': 929,
         'increase': 507,
         'half.': 567,
         'Also,': 1561,
         'once': 1547,
         'strawberries': 539,
         'cook': 4212,
         'down,': 140,
         'masher': 37,
         'break': 188,
         'them': 19689,
         'consistency.': 287,
         'pepper': 4401,
         'kick': 525,
         'fun,': 59,
         'English': 151,
         'muffins,': 161,
         'peanut': 1356,
         'butter': 5572,
         '&': 9664,
         'jelly': 298,
         'sandwiches': 473,
         '(made': 53,
         'wheat': 1778,
         'bread.)': 3,
         'wish': 831,
         'canning': 142,
         'store': 1248,
         'shelf': 48,
         'it!': 4313,
         'started': 876,
         'yesterday': 436,
         'keep': 2162,
         'up.': 1429,
         'back': 3474,
         'coffee': 976,
         'figured': 251,
         'might': 2834,
         'along': 1572,
         'benefits.': 12,
         'OK,': 118,
         'NEVER': 136,
         'buy': 1174,
         'jarred': 130,
         'terrific!': 129,
         'early': 259,
         'day,': 352,
         'later!': 31,
         'pizza,': 66,
         'freezer.': 284,
         'cant': 183,
         'wait.': 63,
         'hint': 419,
         'spice': 1363,
         'red': 4424,
         'omitted': 1607,
         'flakes': 754,
         'small': 3035,
         'delicious.': 3734,
         'again,': 2053,
         'tenderness': 27,
         'rub': 356,
         'right.': 542,
         'cold,': 101,
         'yogurt': 961,
         'whipped': 834,
         'in,': 275,
         'or': 12020,
         'top.': 1375,
         'cumin,': 184,
         'curry,': 57,
         'cinnamon': 2082,
         'try': 8937,
         'Chinese': 203,
         '5.': 153,
         "can't": 3022,
         'resist': 98,
         'splash': 304,
         'too!': 1288,
         '"bake"': 5,
         'squash': 549,
         'microwave': 830,
         '8': 1712,
         'minute': 545,
         'blasts': 1,
         'peel': 343,
         'when': 9491,
         'cool,': 89,
         'freeze': 792,
         'flesh.': 7,
         'Carrots': 32,
         'eaten': 749,
         'right': 3563,
         'highly': 529,
         'recommend': 1542,
         'these': 14418,
         'delicious,': 1064,
         'yet': 1087,
         'treats!': 27,
         'plastic': 293,
         'popsicle': 9,
         'molds': 10,
         'store.': 239,
         'halved': 1284,
         '16': 340,
         'popsicles.': 5,
         'They': 5927,
         'adults': 195,
         'gone': 759,
         'crazy': 379,
         'eating': 2032,
         'And': 2587,
         'since': 4612,
         "they're": 440,
         'them!': 817,
         'Barb': 33,
         'become': 734,
         'favorite!': 215,
         'good,': 3031,
         'modifications': 131,
         '(and': 1001,
         'laziness).': 1,
         'semi': 81,
         'breasts,': 185,
         'browned': 670,
         'them,': 1125,
         'stock': 853,
         'rest': 1884,
         'through': 1258,
         'simmer.': 28,
         'omit': 595,
         'avoid': 195,
         'sugary-ness': 1,
         'commented': 144,
         'PERFECT.': 35,
         'As': 1547,
         'couscous': 179,
         'anything,': 94,
         'cold': 1240,
         'broth': 1953,
         'soak': 317,
         'wait': 2103,
         'breasts': 981,
         'cook.': 325,
         'margarine': 312,
         'garlic-buttery': 1,
         'certainly': 920,
         'disappoint).': 1,
         '#289161.': 1,
         'Miraklegirl!': 4,
         'fantastic!': 779,
         'soft': 1275,
         'chewy': 397,
         'loveddd': 1,
         'friends.': 197,
         'chopped': 3127,
         'mars': 2,
         'bar': 219,
         'chocolate': 4609,
         'chips': 1692,
         'worked': 3075,
         'charm': 25,
         'definitely': 6267,
         'THANKS': 93,
         'Christmas': 1344,
         'party!': 71,
         'Thank': 9735,
         'treat!': 343,
         'dressing': 2160,
         'lot.': 369,
         'sesame': 650,
         'seeds': 805,
         'lamb': 384,
         'marinaded': 64,
         'spices.': 376,
         'posting': 4351,
         'simply': 738,
         'WONDERFUL!': 102,
         'any': 6231,
         'salt,': 1020,
         'substitution': 119,
         "necessity..didn't": 1,
         'hash': 168,
         'browns,': 19,
         'potatoes.': 996,
         'About': 72,
         'half': 7891,
         'peeked': 5,
         'browning': 302,
         'bottom': 1067,
         'potatoes': 3793,
         "weren't": 511,
         'cooking.': 721,
         'needed': 2633,
         'water.': 897,
         'DUH!': 1,
         'remember': 574,
         'how': 5263,
         'added,': 81,
         "I'll": 5414,
         'redo': 7,
         'browns': 104,
         'die': 409,
         'for....': 2,
         'truly!': 1,
         'good..': 25,
         'it..': 61,
         'give': 3294,
         '3.5': 93,
         'stars.': 688,
         'okay': 242,
         'again.<br/><br/>I': 2,
         'drumsticks': 59,
         'wings': 425,
         'grocery': 438,
         'low': 2407,
         'sodium': 453,
         'soy': 1154,
         'sauce.': 3014,
         'forget': 241,
         'marinade': 1074,
         'chicken.': 1191,
         'know': 3493,
         'affected': 64,
         'thicker.': 86,
         'barbecue': 199,
         'move': 69,
         'fluid.': 6,
         'thicken': 702,
         'starch': 190,
         'flour.': 770,
         'stated': 531,
         ':-)': 651,
         'breakfast!': 170,
         'mom': 793,

In [19]:
reviews

,user_id,recipe_id,date,rating,review
370476,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
624300,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
187037,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
706134,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
312179,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...
...,...,...,...,...,...
1013457,1270706,335534,2009-05-17,4,This recipe was great! I made it last night. I...
158736,2282344,8701,2012-06-03,0,This recipe is outstanding. I followed the rec...
1059834,689540,222001,2008-04-08,5,"Well, we were not a crowd but it was a fabulou..."
453285,2000242659,354979,2015-06-02,5,I have been a steak eater and dedicated BBQ gr...
691207,463435,415599,2010-09-30,5,Wonderful and simple to prepare seasoning blen...

5. Напишите несколько версий функции `MAPE` (см. [MAPE](https://en.wikipedia.org/wiki/Mean_absolute_percentage_error)) для расчета среднего процентного отклонения значения рейтинга для отзыва от среднего значения рейтинга для этого отзыва. 
    1. Без использования массивов `numpy` и `numba`
    2. Без использования массивов `numpy`, но с использованием `numba`
    3. С использованием массивов `numpy`, но без использования `numba`
    4. C использованием массивов `numpy` и `numba`
    
Измерьте время выполнения каждой из реализаций.

Замечание: удалите из выборки отзывы с нулевым рейтингом.

In [30]:
mean_rating  = reviews.groupby('recipe_id')['rating'].mean().rename('mean_rating')
reviews_with_mean = reviews.merge(mean_rating, left_on='recipe_id', right_index=True)
reviews_with_mean = reviews_with_mean.query("rating > 0")

In [45]:
def mape_v1(A, F):
    acc = 0
    for idx in range(len(A)):
        acc += abs(A[idx] - F[idx]) / A[idx]
    return acc / len(A) * 100

def mape_v2(A, F):
    return np.mean(np.abs(A - F) / A) * 100

@njit
def mape_v3(A, F):
    return np.mean(np.abs(A - F) / A) * 100

@njit
def mape_v4(A, F):
    acc = 0
    for idx in range(len(A)):
        acc += abs(A[idx] - F[idx]) / A[idx]
    return acc / len(A) * 100

In [37]:
rating = reviews_with_mean['rating'].values
mean_rating = reviews_with_mean['mean_rating'].values

In [38]:
%%time
mape_v1(rating, mean_rating)

Wall time: 809 ms

13.325265503993922

In [49]:
%timeit mape_v2(rating, mean_rating)

930 µs ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [50]:
%timeit mape_v3(rating, mean_rating)

453 µs ± 30.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [51]:
%timeit mape_v4(rating, mean_rating)

585 µs ± 2.62 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)